type useLeaderboardType = {
    TopThreeUsers: {
        User: {
            id: string;
            name: string;
            image: string | null;
            school: string;
            province: string;
            univChoice: string;
            majorChoice: string;
        };
        totalScore: number;
        rank: number;
        maxScore: number;
    }[];
    UserRankingList: {
        rank: number;
        User: {
            id: string;
            name: string;
            image: string | null;
            school: string;
            province: string;
            univChoice: string;
            majorChoice: string;
        };
        totalScore: number;
        maxScore: number;
        totalQuizFinished: number;
        totalQuiz: number;
        accuracy: number;
        averageTime: number;
    }[];
}

export const useLeaderboard: useLeaderboardType = {
    TopThreeUsers: [
        {
            User: {
                id: "user-001",
                name: "Ahmad Rizki",
                image: "https://example.com/avatar-ahmad.jpg",
                school: "SMA Negeri 1 Jakarta",
                province: "DKI Jakarta",
                univChoice: "Universitas Indonesia",
                majorChoice: "Teknik Informatika",
            },
            totalScore: 5100,
            rank: 1,
            maxScore: 5200,
        },
        {
            User: {
                id: "user-002",
                name: "Siti Nurhaliza",
                image: "https://example.com/avatar-siti.jpg",
                school: "SMA Negeri 2 Bandung",
                province: "Jawa Barat",
                univChoice: "Institut Teknologi Bandung",
                majorChoice: "Teknik Mesin",
            },
            totalScore: 4950,
            rank: 2,
            maxScore: 5200,
        },
        {
            User: {
                id: "user-003",
                name: "Budi Santoso",
                image: "https://example.com/avatar-budi.jpg",
                school: "SMA Negeri 3 Surabaya",
                province: "Jawa Timur",
                univChoice: "Universitas Airlangga",
                majorChoice: "Kedokteran",
            },
            totalScore: 4850,
            rank: 3,
            maxScore: 5200,
        },
    ],
    UserRankingList: [
        {
            rank: 1,
            User: {
                id: "user-001",
                name: "Ahmad Rizki",
                image: "https://example.com/avatar-ahmad.jpg",
                school: "SMA Negeri 1 Jakarta",
                province: "DKI Jakarta",
                univChoice: "Universitas Indonesia",
                majorChoice: "Teknik Informatika",
            },
            totalScore: 5100,
            maxScore: 5200,
            totalQuizFinished: 30,
            totalQuiz: 30,
            accuracy: 95.2,
            averageTime: 42.5,
        },
        {
            rank: 2,
            User: {
                id: "user-002",
                name: "Siti Nurhaliza",
                image: "https://example.com/avatar-siti.jpg",
                school: "SMA Negeri 2 Bandung",
                province: "Jawa Barat",
                univChoice: "Institut Teknologi Bandung",
                majorChoice: "Teknik Mesin",
            },
            totalScore: 4950,
            maxScore: 5200,
            totalQuizFinished: 29,
            totalQuiz: 30,
            accuracy: 93.8,
            averageTime: 44.2,
        },
        {
            rank: 3,
            User: {
                id: "user-003",
                name: "Budi Santoso",
                image: "https://example.com/avatar-budi.jpg",
                school: "SMA Negeri 3 Surabaya",
                province: "Jawa Timur",
                univChoice: "Universitas Airlangga",
                majorChoice: "Kedokteran",
            },
            totalScore: 4850,
            maxScore: 5200,
            totalQuizFinished: 28,
            totalQuiz: 30,
            accuracy: 92.5,
            averageTime: 45.8,
        },
        {
            rank: 4,
            User: {
                id: "user-004",
                name: "Rini Wijaya",
                image: null,
                school: "SMA Negeri 1 Medan",
                province: "Sumatera Utara",
                univChoice: "Universitas Sumatera Utara",
                majorChoice: "Teknik Sipil",
            },
            totalScore: 4750,
            maxScore: 5200,
            totalQuizFinished: 27,
            totalQuiz: 30,
            accuracy: 91.0,
            averageTime: 47.3,
        },
        {
            rank: 5,
            User: {
                id: "user-005",
                name: "Doni Hermawan",
                image: "https://example.com/avatar-doni.jpg",
                school: "SMA Negeri 2 Yogyakarta",
                province: "Daerah Istimewa Yogyakarta",
                univChoice: "Universitas Gadjah Mada",
                majorChoice: "Ilmu Komputer",
            },
            totalScore: 4680,
            maxScore: 5200,
            totalQuizFinished: 26,
            totalQuiz: 30,
            accuracy: 89.7,
            averageTime: 48.5,
        },
        {
            rank: 6,
            User: {
                id: "user-006",
                name: "Eka Putri",
                image: "https://example.com/avatar-eka.jpg",
                school: "SMA Negeri 1 Makassar",
                province: "Sulawesi Selatan",
                univChoice: "Universitas Hasanuddin",
                majorChoice: "Farmasi",
            },
            totalScore: 4620,
            maxScore: 5200,
            totalQuizFinished: 25,
            totalQuiz: 30,
            accuracy: 88.5,
            averageTime: 50.2,
        },
        {
            rank: 7,
            User: {
                id: "user-007",
                name: "Fajar Setiawan",
                image: "https://example.com/avatar-fajar.jpg",
                school: "SMA Negeri 1 Semarang",
                province: "Jawa Tengah",
                univChoice: "Universitas Diponegoro",
                majorChoice: "Teknik Elektro",
            },
            totalScore: 4550,
            maxScore: 5200,
            totalQuizFinished: 24,
            totalQuiz: 30,
            accuracy: 87.0,
            averageTime: 52.1,
        },
        {
            rank: 8,
            User: {
                id: "user-008",
                name: "Gina Marlina",
                image: "https://example.com/avatar-gina.jpg",
                school: "SMA Negeri 1 Palembang",
                province: "Sumatera Selatan",
                univChoice: "Universitas Sriwijaya",
                majorChoice: "Hukum",
            },
            totalScore: 4480,
            maxScore: 5200,
            totalQuizFinished: 23,
            totalQuiz: 30,
            accuracy: 85.5,
            averageTime: 54.3,
        },
        {
            rank: 9,
            User: {
                id: "user-009",
                name: "Hendra Kusuma",
                image: "https://example.com/avatar-hendra.jpg",
                school: "SMA Negeri 1 Denpasar",
                province: "Bali",
                univChoice: "Universitas Udayana",
                majorChoice: "Akuntansi",
            },
            totalScore: 4400,
            maxScore: 5200,
            totalQuizFinished: 22,
            totalQuiz: 30,
            accuracy: 84.0,
            averageTime: 56.5,
        },
        {
            rank: 10,
            User: {
                id: "user-010",
                name: "Indah Permata",
                image: "https://example.com/avatar-indah.jpg",
                school: "SMA Negeri 2 Pontianak",
                province: "Kalimantan Barat",
                univChoice: "Universitas Tanjungpura",
                majorChoice: "Biologi",
            },
            totalScore: 4320,
            maxScore: 5200,
            totalQuizFinished: 21,
            totalQuiz: 30,
            accuracy: 82.5,
            averageTime: 58.7,
        },
        {
            rank: 11,
            User: {
                id: "user-011",
                name: "Joko Widodo",
                image: "https://example.com/avatar-joko.jpg",
                school: "SMA Negeri 1 Bogor",
                province: "Jawa Barat",
                univChoice: "Institut Pertanian Bogor",
                majorChoice: "Agronomi",
            },
            totalScore: 4250,
            maxScore: 5200,
            totalQuizFinished: 20,
            totalQuiz: 30,
            accuracy: 81.0,
            averageTime: 60.2,
        },
        {
            rank: 12,
            User: {
                id: "user-012",
                name: "Kirana Dewi",
                image: "https://example.com/avatar-kirana.jpg",
                school: "SMA Negeri 1 Bandung",
                province: "Jawa Barat",
                univChoice: "Universitas Padjadjaran",
                majorChoice: "Psikologi",
            },
            totalScore: 4180,
            maxScore: 5200,
            totalQuizFinished: 19,
            totalQuiz: 30,
            accuracy: 79.5,
            averageTime: 62.1,
        },
        {
            rank: 13,
            User: {
                id: "user-013",
                name: "Luthfi Rahman",
                image: "https://example.com/avatar-luthfi.jpg",
                school: "SMA Negeri 2 Depok",
                province: "Jawa Barat",
                univChoice: "Universitas Gunadarma",
                majorChoice: "Sistem Informasi",
            },
            totalScore: 4110,
            maxScore: 5200,
            totalQuizFinished: 18,
            totalQuiz: 30,
            accuracy: 78.0,
            averageTime: 64.3,
        },
        {
            rank: 14,
            User: {
                id: "user-014",
                name: "Maya Kusuma",
                image: "https://example.com/avatar-maya.jpg",
                school: "SMA Negeri 1 Tangerang",
                province: "Banten",
                univChoice: "Universitas Bina Nusantara",
                majorChoice: "Manajemen",
            },
            totalScore: 4040,
            maxScore: 5200,
            totalQuizFinished: 17,
            totalQuiz: 30,
            accuracy: 76.5,
            averageTime: 66.5,
        },
        {
            rank: 15,
            User: {
                id: "user-015",
                name: "Nadia Pratama",
                image: "https://example.com/avatar-nadia.jpg",
                school: "SMA Negeri 1 Serang",
                province: "Banten",
                univChoice: "Universitas Sultan Ageng Tirtayasa",
                majorChoice: "Teknik Kimia",
            },
            totalScore: 3970,
            maxScore: 5200,
            totalQuizFinished: 16,
            totalQuiz: 30,
            accuracy: 75.0,
            averageTime: 68.7,
        },
        {
            rank: 16,
            User: {
                id: "user-016",
                name: "Oscar Gunawan",
                image: null,
                school: "SMA Negeri 1 Bekasi",
                province: "Jawa Barat",
                univChoice: "Universitas Swadaya Gunung Jati",
                majorChoice: "Desain Grafis",
            },
            totalScore: 3900,
            maxScore: 5200,
            totalQuizFinished: 15,
            totalQuiz: 30,
            accuracy: 73.5,
            averageTime: 70.2,
        },
        {
            rank: 17,
            User: {
                id: "user-017",
                name: "Putri Anggraini",
                image: "https://example.com/avatar-putri.jpg",
                school: "SMA Negeri 2 Cilegon",
                province: "Banten",
                univChoice: "Universitas Negeri Jakarta",
                majorChoice: "Pendidikan Matematika",
            },
            totalScore: 3830,
            maxScore: 5200,
            totalQuizFinished: 14,
            totalQuiz: 30,
            accuracy: 72.0,
            averageTime: 72.4,
        },
        {
            rank: 18,
            User: {
                id: "user-018",
                name: "Quintino Arief",
                image: "https://example.com/avatar-quintino.jpg",
                school: "SMA Negeri 1 Tangerang Selatan",
                province: "Banten",
                univChoice: "Universitas Multimedia Nusantara",
                majorChoice: "Telekomunikasi",
            },
            totalScore: 3760,
            maxScore: 5200,
            totalQuizFinished: 13,
            totalQuiz: 30,
            accuracy: 70.5,
            averageTime: 74.6,
        },
        {
            rank: 19,
            User: {
                id: "user-019",
                name: "Ratna Sari",
                image: "https://example.com/avatar-ratna.jpg",
                school: "SMA Negeri 1 Karawang",
                province: "Jawa Barat",
                univChoice: "Universitas Singaperbangsa Karawang",
                majorChoice: "Teknik Mesin",
            },
            totalScore: 3690,
            maxScore: 5200,
            totalQuizFinished: 12,
            totalQuiz: 30,
            accuracy: 69.0,
            averageTime: 76.8,
        },
        {
            rank: 20,
            User: {
                id: "user-020",
                name: "Safira Putri",
                image: "https://example.com/avatar-safira.jpg",
                school: "SMA Negeri 1 Subang",
                province: "Jawa Barat",
                univChoice: "Universitas Subang",
                majorChoice: "Ilmu Komunikasi",
            },
            totalScore: 3620,
            maxScore: 5200,
            totalQuizFinished: 11,
            totalQuiz: 30,
            accuracy: 67.5,
            averageTime: 79.0,
        },
        {
            rank: 21,
            User: {
                id: "user-021",
                name: "Taufiq Hidayat",
                image: "https://example.com/avatar-taufiq.jpg",
                school: "SMA Negeri 1 Bandung Barat",
                province: "Jawa Barat",
                univChoice: "Universitas Pasundan",
                majorChoice: "Teknik Sipil",
            },
            totalScore: 3550,
            maxScore: 5200,
            totalQuizFinished: 10,
            totalQuiz: 30,
            accuracy: 66.0,
            averageTime: 81.2,
        },
        {
            rank: 22,
            User: {
                id: "user-022",
                name: "Utami Maharani",
                image: "https://example.com/avatar-utami.jpg",
                school: "SMA Negeri 1 Cimahi",
                province: "Jawa Barat",
                univChoice: "Universitas Pendidikan Indonesia",
                majorChoice: "Pendidikan Fisika",
            },
            totalScore: 3480,
            maxScore: 5200,
            totalQuizFinished: 9,
            totalQuiz: 30,
            accuracy: 64.5,
            averageTime: 83.4,
        },
        {
            rank: 23,
            User: {
                id: "user-023",
                name: "Vicky Prabowo",
                image: "https://example.com/avatar-vicky.jpg",
                school: "SMA Negeri 1 Purwakarta",
                province: "Jawa Barat",
                univChoice: "Universitas Purwakarta",
                majorChoice: "Manajemen Industri",
            },
            totalScore: 3410,
            maxScore: 5200,
            totalQuizFinished: 8,
            totalQuiz: 30,
            accuracy: 63.0,
            averageTime: 85.6,
        },
        {
            rank: 24,
            User: {
                id: "user-024",
                name: "Winda Ramadhani",
                image: "https://example.com/avatar-winda.jpg",
                school: "SMA Negeri 1 Indramayu",
                province: "Jawa Barat",
                univChoice: "Universitas Indraprasta PGRI",
                majorChoice: "Akuntansi",
            },
            totalScore: 3340,
            maxScore: 5200,
            totalQuizFinished: 7,
            totalQuiz: 30,
            accuracy: 61.5,
            averageTime: 87.8,
        },
        {
            rank: 25,
            User: {
                id: "user-025",
                name: "Xavier Wijaya",
                image: "https://example.com/avatar-xavier.jpg",
                school: "SMA Negeri 1 Kuningan",
                province: "Jawa Barat",
                univChoice: "Universitas Kuningan",
                majorChoice: "Hukum Bisnis",
            },
            totalScore: 3270,
            maxScore: 5200,
            totalQuizFinished: 6,
            totalQuiz: 30,
            accuracy: 60.0,
            averageTime: 90.0,
        },
        {
            rank: 26,
            User: {
                id: "user-026",
                name: "Yuliana Sari",
                image: "https://example.com/avatar-yuliana.jpg",
                school: "SMA Negeri 1 Ciamis",
                province: "Jawa Barat",
                univChoice: "Universitas Ciamis",
                majorChoice: "Agribisnis",
            },
            totalScore: 3200,
            maxScore: 5200,
            totalQuizFinished: 5,
            totalQuiz: 30,
            accuracy: 58.5,
            averageTime: 92.2,
        },
        {
            rank: 27,
            User: {
                id: "user-027",
                name: "Zainal Arifin",
                image: "https://example.com/avatar-zainal.jpg",
                school: "SMA Negeri 1 Banjar",
                province: "Jawa Barat",
                univChoice: "Universitas Swadaya Gunung Jati Cirebon",
                majorChoice: "Teknik Industri",
            },
            totalScore: 3130,
            maxScore: 5200,
            totalQuizFinished: 4,
            totalQuiz: 30,
            accuracy: 57.0,
            averageTime: 94.4,
        },
        {
            rank: 28,
            User: {
                id: "user-028",
                name: "Alma Kusuma",
                image: null,
                school: "SMA Negeri 1 Majalengka",
                province: "Jawa Barat",
                univChoice: "Universitas Majalengka",
                majorChoice: "Pendidikan Kimia",
            },
            totalScore: 3060,
            maxScore: 5200,
            totalQuizFinished: 3,
            totalQuiz: 30,
            accuracy: 55.5,
            averageTime: 96.6,
        },
        {
            rank: 29,
            User: {
                id: "user-029",
                name: "Bambang Suryanto",
                image: "https://example.com/avatar-bambang.jpg",
                school: "SMA Negeri 1 Garut",
                province: "Jawa Barat",
                univChoice: "Universitas Garut",
                majorChoice: "Teknik Komputer",
            },
            totalScore: 2990,
            maxScore: 5200,
            totalQuizFinished: 2,
            totalQuiz: 30,
            accuracy: 54.0,
            averageTime: 98.8,
        },
        {
            rank: 30,
            User: {
                id: "user-030",
                name: "Citra Dewi",
                image: "https://example.com/avatar-citra.jpg",
                school: "SMA Negeri 1 Tasikmalaya",
                province: "Jawa Barat",
                univChoice: "Universitas Tasikmalaya",
                majorChoice: "Kesehatan Masyarakat",
            },
            totalScore: 2920,
            maxScore: 5200,
            totalQuizFinished: 1,
            totalQuiz: 30,
            accuracy: 52.5,
            averageTime: 101.0,
        },
    ],
};